name: MyBlog

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=wordpress
    volumes:
      - mysql-data:/var/lib/mysql
      - /tmp/mysqlconf:/etc/mysql/conf.d
    restart: always
    networks:
      - blog
    
  wordpress:
    container_name: wordpress
    image: wordpress
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - blog
    depends_on:
      - mysql


volumes:
  mysql-data:
  wordpress:


networks:
  blog: